doctrine:
    dbal:
        default_connection: default
        # url: '%env(resolve:DATABASE_URL)%'
        connections:
            default:
                host: '%env(DATABASE_HOST)%'
                port: '%env(DATABASE_PORT)%'
                dbname: '%env(DATABASE_NAME)%'
                user: '%env(DATABASE_USER)%'
                password: '%env(DATABASE_PASSWORD)%'
                use_savepoints: true
            test:
                host: '%env(TEST_DATABASE_HOST)%'
                port: '%env(TEST_DATABASE_PORT)%'
                dbname: '%env(TEST_DATABASE_NAME)%'
                user: '%env(TEST_DATABASE_USER)%'
                password: '%env(TEST_DATABASE_PASSWORD)%'


        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Product:
                type: yml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Product/Infrastructure/Persistence/Doctrine/Mappings'
                prefix: 'Roadsurfer\Product\Domain\Entity'
                alias: Product

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
