version: '3.8'

services:
  app:
    build: .
    working_dir: /app
    container_name: fruits-and-vegetables
    command: php -S 0.0.0.0:8080 -t /app/public
    ports:
      - "8080:8080"
    volumes:
      - ..:/app
  db:
    image: mysql:latest
    container_name: roadsurfer_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: roadsurfer
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
